version: '3.4'

services:
  tictactoe:
    image: tictactoe
    build:
      context: web
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
  tictactoeapi:
    image: tictactoeapi
    build:
      context: .
      dockerfile: api/src/TicTacToe.Api/Dockerfile
    ports:
      - 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
