CREATE DATABASE TicTacToeDB;
GO

USE TicTacToeDB;
GO

CREATE TABLE Games (
    ID UNIQUEIDENTIFIER PRIMARY KEY default NEWID()
)
GO

CREATE TABLE GameStates(
    ID UNIQUEIDENTIFIER PRIMARY KEY default NEWID(),
    GameID UNIQUEIDENTIFIER NOT NULL,
    Squares varchar(255) NOT NULL,
    TurnNumber int NOT NULL
)
